name: Profile Photo Submission
description: Add/Update Profile Photo on website
title: "[Website]: Profile Photo for "
assignees:
  - ntlhui
body:
  - type: markdown
    attributes:
      value: |
        Photos should be a clear representative photo of each person, suitable
        for public distribution.  Submitted photos should be PNG or JPEG
        format, scaled to 200x200px.  Filename should be {year}_{name}.{ext}.
        Please attach the image to this issue
  - type: input
    id: name
    attributes:
      label: Name
      description: Please enter the name that this profile should be put under on the website
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Image Submission
      description: By submitting this issue, you agree that the attached image is permissible for publication on the E4E Website
      options:
        - label: I agree to allow this image to be published
          required: true