name: BibTex2HTML Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        wget http://www.lri.fr/~filliatr/ftp/bibtex2html/bibtex2html-1.99-linux.tar.gz -O /tmp/bibtex.tar.gz
        mkdir /tmp/bibtex
        tar -xzf /tmp/bibtex.tar.gz -C /tmp/bibtex
        echo `/tmp/bibtex/bibtex2html-1.99-linux` >> $GITHUB_PATH
    - name: Build
      run: |
        cd publications
        /bin/bash ./createHTML.sh
        cd ..
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./publications/publications.html