name: BibTex2HTML Build

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install toolchain
      run: |
        sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
        sudo rm -f /var/lib/man-db/auto-update
        sudo apt-get update
        sudo apt-get install bibtex2html
    - name: Build
      run: |
        cd publications
        bibtex2html -w -d -nobibsource -nofooter -r -nodoc -dl -s ieeetr -noheader -html-entities publications.bib
        cd ..
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: ./publications/publications.html